### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by yochananmarqos** [vineetred/flowy#19]
**Describe the bug**
Building 0.2.0 from source:

```
$ flowy 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:181:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ RUST_BACKTRACE=full flowy
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:181:18
stack backtrace:
   0:     0x5562d184c005 - backtrace::backtrace::libunwind::trace::he332cdcbba52aaad
                               at /build/rust/src/rustc-1.44.1-src/vendor/backtrace/src/backtrace/libunwind.rs:86
   1:     0x5562d184c005 - backtrace::backtrace::trace_unsynchronized::hef03e255f1bf514f
                               at /build/rust/src/rustc-1.44.1-src/vendor/backtrace/src/backtrace/mod.rs:66
   2:     0x5562d184c005 - std::sys_common::backtrace::_print_fmt::hb165a755ba92b1b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5562d184c005 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h45e432f08dbe7d76
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5562d18734cc - core::fmt::write::h73c3f84d9cf018c3
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5562d1844dd3 - std::io::Write::write_fmt::h8ac7e773e542f3e7
                               at src/libstd/io/mod.rs:1504
   6:     0x5562d184e750 - std::sys_common::backtrace::_print::he776a3581f8527e1
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5562d184e750 - std::sys_common::backtrace::print::h969151019a7e30fc
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5562d184e750 - std::panicking::default_hook::{{closure}}::hac98c3c5d7e976ca
                               at src/libstd/panicking.rs:198
   9:     0x5562d184e49c - std::panicking::default_hook::h4e2eee37e61c3121
                               at src/libstd/panicking.rs:218
  10:     0x5562d184eda1 - std::panicking::rust_panic_with_hook::heb6c94442a23e0d6
                               at src/libstd/panicking.rs:511
  11:     0x5562d184e98b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x5562d1871bc1 - core::panicking::panic_fmt::h4cb2b865a9fe0609
                               at src/libcore/panicking.rs:111
  13:     0x5562d18719e3 - core::option::expect_none_failed::h9d99908668e725ae
                               at src/libcore/option.rs:1268
  14:     0x5562d162f4a8 - flowy::set_times::hdc94ccdd1c762f84
  15:     0x5562d1629d54 - flowy::main::hd4de0d3e0a035220
  16:     0x5562d1628a73 - std::rt::lang_start::{{closure}}::he9ae725c8e451724
  17:     0x5562d184f2a8 - std::rt::lang_start_internal::{{closure}}::hbfd5d2d2e29ca3fd
                               at src/libstd/rt.rs:52
  18:     0x5562d184f2a8 - std::panicking::try::do_call::h2185ede4ed6d658a
                               at src/libstd/panicking.rs:331
  19:     0x5562d184f2a8 - std::panicking::try::h86936ac9fc3ad867
                               at src/libstd/panicking.rs:274
  20:     0x5562d184f2a8 - std::panic::catch_unwind::h724716514d9df9d1
                               at src/libstd/panic.rs:394
  21:     0x5562d184f2a8 - std::rt::lang_start_internal::he9685c4c8d86dfd9
                               at src/libstd/rt.rs:51
  22:     0x5562d1629f02 - main
  23:     0x7f3cf262c002 - __libc_start_main
  24:     0x5562d16210ee - _start
  25:                0x0 - <unknown>
```

Building from latest commit:

```
$ flowy
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

No difference running with `RUST_BACKTRACE`

**To Reproduce**
Build with Rust 1.44.1:

```
cargo build --release --locked --all-features
```

I also tried without `--locked` and `--all-features`.

**Desktop**
 - OS: Manjaro GNOME

**Comment by vineetred** [comment]
Hey! So this is a known bug -- flowy needs arguments to run in the current version.  Without arguments, in panics and shuts down. Try running it with ```flowy --dir <PATH TO DIR>``` and it should run fine.

**Comment by vineetred** [comment]
Build and run the newest version -- bug has been fixed.
